/**
 * Database Seed Script
 * Creates test users and sample data
 */

require('dotenv').config();
const { sequelize } = require('../config/database');
const { User, Department, Employee } = require('../models');
const { encryptionService } = require('../utils/encryption');

async function seed() {
  try {
    console.log('开始数据库种子操作...');

    // Sync database (create tables if they don't exist)
    await sequelize.sync();

    console.log('清理现有数据...');
    // Clear existing data (for dev/test only!)
    await User.destroy({ where: {}, force: true });
    await Employee.destroy({ where: {}, force: true });
    await Department.destroy({ where: {}, force: true });

    console.log('创建部门数据...');
    // Create departments - 参考sample_data结构
    // Note: department_id will be auto-generated by Sequelize (UUID)
    const departments = await Department.bulkCreate([
      {
        name: '技术部',
        code: 'TECH',
        description: '负责公司技术研发和产品开发',
        created_by: 'system'
      },
      {
        name: '人力资源部',
        code: 'HR',
        description: '负责人事管理、招聘和培训',
        created_by: 'system'
      },
      {
        name: '市场部',
        code: 'MKT',
        description: '负责市场营销和品牌推广',
        created_by: 'system'
      },
      {
        name: '财务部',
        code: 'FIN',
        description: '负责财务管理和会计核算',
        created_by: 'system'
      },
      {
        name: '产品部',
        code: 'PROD',
        description: '负责产品规划和设计',
        created_by: 'system'
      },
      {
        name: '运营部',
        code: 'OPS',
        description: '负责日常运营和客户服务',
        created_by: 'system'
      },
      {
        name: '行政部',
        code: 'ADMIN',
        description: '负责行政管理和后勤保障',
        created_by: 'system'
      },
      {
        name: '销售部',
        code: 'SALES',
        description: '负责销售和客户关系管理',
        created_by: 'system'
      },
      {
        name: '客服部',
        code: 'CS',
        description: '负责客户服务和售后支持',
        created_by: 'system'
      }
    ]);

    console.log(`创建了 ${departments.length} 个部门`);

    console.log('创建测试用户账号...');
    // Create test users with hashed passwords
    const defaultPassword = 'password123'; // Default password for all test accounts
    const passwordHash = await encryptionService.hashPassword(defaultPassword);

    const users = [];

    // Admin user
    // Note: user_id will be auto-generated by Sequelize (UUID)
    const adminUser = await User.create({
      username: 'admin',
      password_hash: passwordHash,
      display_name: '系统管理员',
      email: 'admin@hrsystem.com',
      phone: '13800000001',
      role: 'admin',
      permissions: ['*'],
      status: 'active',
      is_active: true,
      created_by: 'system'
    });
    users.push(adminUser);

    // HR user
    const hrUser = await User.create({
      username: 'hr_admin',
      password_hash: passwordHash,
      display_name: '人力资源管理员',
      email: 'hr@hrsystem.com',
      phone: '13800000002',
      role: 'hr',
      permissions: ['employees:read', 'employees:write', 'departments:read'],
      status: 'active',
      is_active: true,
      created_by: 'system'
    });
    users.push(hrUser);

    // Manager user
    const managerUser = await User.create({
      username: 'manager',
      password_hash: passwordHash,
      display_name: '部门经理',
      email: 'manager@hrsystem.com',
      phone: '13800000003',
      role: 'manager',
      permissions: ['employees:read', 'departments:read'],
      status: 'active',
      is_active: true,
      created_by: 'system'
    });
    users.push(managerUser);

    // Regular employee user
    const employeeUser = await User.create({
      username: 'employee',
      password_hash: passwordHash,
      display_name: '普通员工',
      email: 'employee@hrsystem.com',
      phone: '13800000004',
      role: 'employee',
      permissions: ['employees:read:self'],
      status: 'active',
      is_active: true,
      created_by: 'system'
    });
    users.push(employeeUser);

    console.log(`创建了 ${users.length} 个测试用户`);

    console.log('创建示例员工数据...');
    // Create sample employee records - 参考sample_data结构
    // Note: employee_id will be auto-generated by Sequelize (UUID)
    // We need to use actual department IDs from the created departments
    const employeeData = [
      {
        number: 'EMP001',
        name: '张伟',
        phone: '13812345678',
        idCard: '110101199001011234',
        birthDate: '1990-01-01',
        email: 'zhangwei@company.com',
        department_index: 0, // 技术部
        position: 'Java工程师',
        employment_type: 'full_time',
        entry_date: '2023-01-15',
        status: 'active',
        gender: 'male',
        address: '北京市朝阳区建国路88号'
      },
      {
        number: 'EMP002',
        name: '李娜',
        phone: '13823456789',
        idCard: '110101199102021234',
        birthDate: '1991-02-02',
        email: 'lina@company.com',
        department_index: 1, // 人力资源部
        position: 'HR专员',
        employment_type: 'full_time',
        entry_date: '2023-03-20',
        status: 'active',
        gender: 'female',
        address: '北京市海淀区中关村大街1号'
      },
      {
        number: 'EMP003',
        name: '王强',
        phone: '13834567890',
        idCard: '110101199203031234',
        birthDate: '1992-03-03',
        email: 'wangqiang@company.com',
        department_index: 2, // 市场部
        position: '市场经理',
        employment_type: 'full_time',
        entry_date: '2022-06-10',
        status: 'active',
        gender: 'male',
        address: '北京市东城区王府井大街88号'
      },
      {
        number: 'EMP004',
        name: '刘芳',
        phone: '13845678901',
        idCard: '110101199304041234',
        birthDate: '1993-04-04',
        email: 'liufang@company.com',
        department_index: 3, // 财务部
        position: '会计',
        employment_type: 'full_time',
        entry_date: '2022-09-01',
        status: 'active',
        gender: 'female',
        address: '北京市西城区金融街25号'
      },
      {
        number: 'EMP005',
        name: '陈明',
        phone: '13856789012',
        idCard: '110101199405051234',
        birthDate: '1994-05-05',
        email: 'chenming@company.com',
        department_index: 4, // 产品部
        position: '产品经理',
        employment_type: 'full_time',
        entry_date: '2023-05-15',
        status: 'active',
        gender: 'male',
        address: '北京市朝阳区望京SOHO'
      },
      {
        number: 'EMP006',
        name: '赵敏',
        phone: '13867890123',
        idCard: '110101199506061234',
        birthDate: '1995-06-06',
        email: 'zhaomin@company.com',
        department_index: 5, // 运营部
        position: '运营专员',
        employment_type: 'full_time',
        entry_date: '2023-07-01',
        status: 'active',
        gender: 'female',
        address: '北京市丰台区丽泽金融商务区'
      },
      {
        number: 'EMP007',
        name: '孙磊',
        phone: '13878901234',
        idCard: '110101199607071234',
        birthDate: '1996-07-07',
        email: 'sunlei@company.com',
        department_index: 6, // 行政部
        position: '行政助理',
        employment_type: 'full_time',
        entry_date: '2024-01-10',
        status: 'active',
        gender: 'male',
        address: '北京市石景山区万达广场'
      },
      {
        number: 'EMP008',
        name: '周婷',
        phone: '13889012345',
        idCard: '110101199708081234',
        birthDate: '1997-08-08',
        email: 'zhouting@company.com',
        department_index: 7, // 销售部
        position: '销售代表',
        employment_type: 'full_time',
        entry_date: '2024-02-20',
        status: 'active',
        gender: 'female',
        address: '北京市通州区万达广场'
      },
      {
        number: 'EMP009',
        name: '吴鹏',
        phone: '13890123456',
        idCard: '110101199809091234',
        birthDate: '1998-09-09',
        email: 'wupeng@company.com',
        department_index: 0, // 技术部
        position: '前端工程师',
        employment_type: 'full_time',
        entry_date: '2024-03-01',
        status: 'active',
        gender: 'male',
        address: '北京市昌平区回龙观'
      },
      {
        number: 'EMP010',
        name: '郑雪',
        phone: '13801234567',
        idCard: '110101199910101234',
        birthDate: '1999-10-10',
        email: 'zhengxue@company.com',
        department_index: 1, // 人力资源部
        position: '招聘专员',
        employment_type: 'full_time',
        entry_date: '2024-04-15',
        status: 'active',
        gender: 'female',
        address: '北京市大兴区亦庄经济开发区'
      },
      {
        number: 'EMP011',
        name: '马超',
        phone: '13812340001',
        idCard: '110101200001011234',
        birthDate: '2000-01-01',
        email: 'machao@company.com',
        department_index: 4, // 产品部
        position: 'UI设计师',
        employment_type: 'intern',
        entry_date: '2024-09-01',
        status: 'pending',
        gender: 'male',
        address: '北京市海淀区五道口'
      },
      {
        number: 'EMP012',
        name: '黄莉',
        phone: '13823450002',
        idCard: '110101200102021234',
        birthDate: '2001-02-02',
        email: 'huangli@company.com',
        department_index: 2, // 市场部
        position: '市场助理',
        employment_type: 'part_time',
        entry_date: '2024-10-01',
        status: 'pending',
        gender: 'female',
        address: '北京市朝阳区三里屯'
      }
    ];

    const employees = [];
    for (const data of employeeData) {
      const employee = Employee.build({
        employee_number: data.number,
        email: data.email,
        department_id: departments[data.department_index].department_id,
        position: data.position,
        employment_type: data.employment_type,
        entry_date: new Date(data.entry_date),
        status: data.status,
        gender: data.gender,
        address: data.address,
        created_by: 'system'
      });

      // Set encrypted fields
      employee.setName(data.name);
      employee.setPhone(data.phone);
      employee.setIdCard(data.idCard);
      employee.setBirthDate(data.birthDate);

      await employee.save();
      employees.push(employee);
    }

    console.log(`创建了 ${employees.length} 个示例员工`);

    console.log('\n========================================');
    console.log('数据库种子操作完成！');
    console.log('========================================');
    console.log('\n测试账号信息：');
    console.log('----------------------------------------');
    console.log('管理员账号:');
    console.log('  用户名: admin');
    console.log('  密码: password123');
    console.log('  角色: 系统管理员\n');

    console.log('HR管理员账号:');
    console.log('  用户名: hr_admin');
    console.log('  密码: password123');
    console.log('  角色: 人力资源管理员\n');

    console.log('部门经理账号:');
    console.log('  用户名: manager');
    console.log('  密码: password123');
    console.log('  角色: 部门经理\n');

    console.log('普通员工账号:');
    console.log('  用户名: employee');
    console.log('  密码: password123');
    console.log('  角色: 普通员工\n');
    console.log('========================================\n');

    process.exit(0);
  } catch (error) {
    console.error('数据库种子操作失败:', error);
    console.error(error.stack);
    process.exit(1);
  }
}

// Run seed if called directly
if (require.main === module) {
  seed();
}

module.exports = seed;
